/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ReportRouteImport } from './routes/report'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as ShareTokenRouteImport } from './routes/share.$token'
import { Route as ProposalTokenRouteImport } from './routes/proposal.$token'
import { Route as PeekTokenRouteImport } from './routes/peek.$token'
import { Route as AppTodayRouteImport } from './routes/_app/today'
import { Route as AppTeamRouteImport } from './routes/_app/team'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppReportsRouteImport } from './routes/_app/reports'
import { Route as AppProjectsRouteImport } from './routes/_app/projects'
import { Route as AppPipelineRouteImport } from './routes/_app/pipeline'
import { Route as AppPayrollRouteImport } from './routes/_app/payroll'
import { Route as AppOpportunitiesRouteImport } from './routes/_app/opportunities'
import { Route as AppHelpRouteImport } from './routes/_app/help'
import { Route as AppFollowupsRouteImport } from './routes/_app/followups'
import { Route as AppEmailsRouteImport } from './routes/_app/emails'
import { Route as AppDiscoverRouteImport } from './routes/_app/discover'
import { Route as AppContactsRouteImport } from './routes/_app/contacts'
import { Route as AppCompaniesRouteImport } from './routes/_app/companies'
import { Route as AppCallsRouteImport } from './routes/_app/calls'
import { Route as AppBillingRouteImport } from './routes/_app/billing'
import { Route as AppActivitiesRouteImport } from './routes/_app/activities'
import { Route as ApiGmailDisconnectRouteImport } from './routes/api/gmail/disconnect'
import { Route as ApiGmailConnectRouteImport } from './routes/api/gmail/connect'
import { Route as ApiGmailCallbackRouteImport } from './routes/api/gmail/callback'
import { Route as ApiCronSweepRouteImport } from './routes/api/cron/sweep'
import { Route as ApiAuthSignupRouteImport } from './routes/api/auth/signup'
import { Route as ApiAuthLogoutRouteImport } from './routes/api/auth/logout'
import { Route as ApiAuthLoginRouteImport } from './routes/api/auth/login'
import { Route as AppDealsDealIdRouteImport } from './routes/_app/deals.$dealId'
import { Route as AppContactsContactIdRouteImport } from './routes/_app/contacts_.$contactId'
import { Route as AppCompaniesCompanyIdRouteImport } from './routes/_app/companies_.$companyId'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const ShareTokenRoute = ShareTokenRouteImport.update({
  id: '/share/$token',
  path: '/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalTokenRoute = ProposalTokenRouteImport.update({
  id: '/proposal/$token',
  path: '/proposal/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PeekTokenRoute = PeekTokenRouteImport.update({
  id: '/peek/$token',
  path: '/peek/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTodayRoute = AppTodayRouteImport.update({
  id: '/today',
  path: '/today',
  getParentRoute: () => AppRoute,
} as any)
const AppTeamRoute = AppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppPipelineRoute = AppPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AppRoute,
} as any)
const AppPayrollRoute = AppPayrollRouteImport.update({
  id: '/payroll',
  path: '/payroll',
  getParentRoute: () => AppRoute,
} as any)
const AppOpportunitiesRoute = AppOpportunitiesRouteImport.update({
  id: '/opportunities',
  path: '/opportunities',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppRoute,
} as any)
const AppFollowupsRoute = AppFollowupsRouteImport.update({
  id: '/followups',
  path: '/followups',
  getParentRoute: () => AppRoute,
} as any)
const AppEmailsRoute = AppEmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => AppRoute,
} as any)
const AppDiscoverRoute = AppDiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsRoute = AppContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AppRoute,
} as any)
const AppCompaniesRoute = AppCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AppRoute,
} as any)
const AppCallsRoute = AppCallsRouteImport.update({
  id: '/calls',
  path: '/calls',
  getParentRoute: () => AppRoute,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRoute,
} as any)
const AppActivitiesRoute = AppActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => AppRoute,
} as any)
const ApiGmailDisconnectRoute = ApiGmailDisconnectRouteImport.update({
  id: '/api/gmail/disconnect',
  path: '/api/gmail/disconnect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGmailConnectRoute = ApiGmailConnectRouteImport.update({
  id: '/api/gmail/connect',
  path: '/api/gmail/connect',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGmailCallbackRoute = ApiGmailCallbackRouteImport.update({
  id: '/api/gmail/callback',
  path: '/api/gmail/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCronSweepRoute = ApiCronSweepRouteImport.update({
  id: '/api/cron/sweep',
  path: '/api/cron/sweep',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignupRoute = ApiAuthSignupRouteImport.update({
  id: '/api/auth/signup',
  path: '/api/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLogoutRoute = ApiAuthLogoutRouteImport.update({
  id: '/api/auth/logout',
  path: '/api/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthLoginRoute = ApiAuthLoginRouteImport.update({
  id: '/api/auth/login',
  path: '/api/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppDealsDealIdRoute = AppDealsDealIdRouteImport.update({
  id: '/deals/$dealId',
  path: '/deals/$dealId',
  getParentRoute: () => AppRoute,
} as any)
const AppContactsContactIdRoute = AppContactsContactIdRouteImport.update({
  id: '/contacts_/$contactId',
  path: '/contacts/$contactId',
  getParentRoute: () => AppRoute,
} as any)
const AppCompaniesCompanyIdRoute = AppCompaniesCompanyIdRouteImport.update({
  id: '/companies_/$companyId',
  path: '/companies/$companyId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/report': typeof ReportRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/activities': typeof AppActivitiesRoute
  '/billing': typeof AppBillingRoute
  '/calls': typeof AppCallsRoute
  '/companies': typeof AppCompaniesRoute
  '/contacts': typeof AppContactsRoute
  '/discover': typeof AppDiscoverRoute
  '/emails': typeof AppEmailsRoute
  '/followups': typeof AppFollowupsRoute
  '/help': typeof AppHelpRoute
  '/opportunities': typeof AppOpportunitiesRoute
  '/payroll': typeof AppPayrollRoute
  '/pipeline': typeof AppPipelineRoute
  '/projects': typeof AppProjectsRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/team': typeof AppTeamRoute
  '/today': typeof AppTodayRoute
  '/peek/$token': typeof PeekTokenRoute
  '/proposal/$token': typeof ProposalTokenRoute
  '/share/$token': typeof ShareTokenRoute
  '/companies/$companyId': typeof AppCompaniesCompanyIdRoute
  '/contacts/$contactId': typeof AppContactsContactIdRoute
  '/deals/$dealId': typeof AppDealsDealIdRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/cron/sweep': typeof ApiCronSweepRoute
  '/api/gmail/callback': typeof ApiGmailCallbackRoute
  '/api/gmail/connect': typeof ApiGmailConnectRoute
  '/api/gmail/disconnect': typeof ApiGmailDisconnectRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/report': typeof ReportRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/activities': typeof AppActivitiesRoute
  '/billing': typeof AppBillingRoute
  '/calls': typeof AppCallsRoute
  '/companies': typeof AppCompaniesRoute
  '/contacts': typeof AppContactsRoute
  '/discover': typeof AppDiscoverRoute
  '/emails': typeof AppEmailsRoute
  '/followups': typeof AppFollowupsRoute
  '/help': typeof AppHelpRoute
  '/opportunities': typeof AppOpportunitiesRoute
  '/payroll': typeof AppPayrollRoute
  '/pipeline': typeof AppPipelineRoute
  '/projects': typeof AppProjectsRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/team': typeof AppTeamRoute
  '/today': typeof AppTodayRoute
  '/peek/$token': typeof PeekTokenRoute
  '/proposal/$token': typeof ProposalTokenRoute
  '/share/$token': typeof ShareTokenRoute
  '/': typeof AppIndexRoute
  '/companies/$companyId': typeof AppCompaniesCompanyIdRoute
  '/contacts/$contactId': typeof AppContactsContactIdRoute
  '/deals/$dealId': typeof AppDealsDealIdRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/cron/sweep': typeof ApiCronSweepRoute
  '/api/gmail/callback': typeof ApiGmailCallbackRoute
  '/api/gmail/connect': typeof ApiGmailConnectRoute
  '/api/gmail/disconnect': typeof ApiGmailDisconnectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/report': typeof ReportRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_app/activities': typeof AppActivitiesRoute
  '/_app/billing': typeof AppBillingRoute
  '/_app/calls': typeof AppCallsRoute
  '/_app/companies': typeof AppCompaniesRoute
  '/_app/contacts': typeof AppContactsRoute
  '/_app/discover': typeof AppDiscoverRoute
  '/_app/emails': typeof AppEmailsRoute
  '/_app/followups': typeof AppFollowupsRoute
  '/_app/help': typeof AppHelpRoute
  '/_app/opportunities': typeof AppOpportunitiesRoute
  '/_app/payroll': typeof AppPayrollRoute
  '/_app/pipeline': typeof AppPipelineRoute
  '/_app/projects': typeof AppProjectsRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/team': typeof AppTeamRoute
  '/_app/today': typeof AppTodayRoute
  '/peek/$token': typeof PeekTokenRoute
  '/proposal/$token': typeof ProposalTokenRoute
  '/share/$token': typeof ShareTokenRoute
  '/_app/': typeof AppIndexRoute
  '/_app/companies_/$companyId': typeof AppCompaniesCompanyIdRoute
  '/_app/contacts_/$contactId': typeof AppContactsContactIdRoute
  '/_app/deals/$dealId': typeof AppDealsDealIdRoute
  '/api/auth/login': typeof ApiAuthLoginRoute
  '/api/auth/logout': typeof ApiAuthLogoutRoute
  '/api/auth/signup': typeof ApiAuthSignupRoute
  '/api/cron/sweep': typeof ApiCronSweepRoute
  '/api/gmail/callback': typeof ApiGmailCallbackRoute
  '/api/gmail/connect': typeof ApiGmailConnectRoute
  '/api/gmail/disconnect': typeof ApiGmailDisconnectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/report'
    | '/robots.txt'
    | '/signup'
    | '/sitemap.xml'
    | '/activities'
    | '/billing'
    | '/calls'
    | '/companies'
    | '/contacts'
    | '/discover'
    | '/emails'
    | '/followups'
    | '/help'
    | '/opportunities'
    | '/payroll'
    | '/pipeline'
    | '/projects'
    | '/reports'
    | '/settings'
    | '/team'
    | '/today'
    | '/peek/$token'
    | '/proposal/$token'
    | '/share/$token'
    | '/companies/$companyId'
    | '/contacts/$contactId'
    | '/deals/$dealId'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/signup'
    | '/api/cron/sweep'
    | '/api/gmail/callback'
    | '/api/gmail/connect'
    | '/api/gmail/disconnect'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/report'
    | '/robots.txt'
    | '/signup'
    | '/sitemap.xml'
    | '/activities'
    | '/billing'
    | '/calls'
    | '/companies'
    | '/contacts'
    | '/discover'
    | '/emails'
    | '/followups'
    | '/help'
    | '/opportunities'
    | '/payroll'
    | '/pipeline'
    | '/projects'
    | '/reports'
    | '/settings'
    | '/team'
    | '/today'
    | '/peek/$token'
    | '/proposal/$token'
    | '/share/$token'
    | '/'
    | '/companies/$companyId'
    | '/contacts/$contactId'
    | '/deals/$dealId'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/signup'
    | '/api/cron/sweep'
    | '/api/gmail/callback'
    | '/api/gmail/connect'
    | '/api/gmail/disconnect'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/report'
    | '/robots.txt'
    | '/signup'
    | '/sitemap.xml'
    | '/_app/activities'
    | '/_app/billing'
    | '/_app/calls'
    | '/_app/companies'
    | '/_app/contacts'
    | '/_app/discover'
    | '/_app/emails'
    | '/_app/followups'
    | '/_app/help'
    | '/_app/opportunities'
    | '/_app/payroll'
    | '/_app/pipeline'
    | '/_app/projects'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/team'
    | '/_app/today'
    | '/peek/$token'
    | '/proposal/$token'
    | '/share/$token'
    | '/_app/'
    | '/_app/companies_/$companyId'
    | '/_app/contacts_/$contactId'
    | '/_app/deals/$dealId'
    | '/api/auth/login'
    | '/api/auth/logout'
    | '/api/auth/signup'
    | '/api/cron/sweep'
    | '/api/gmail/callback'
    | '/api/gmail/connect'
    | '/api/gmail/disconnect'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  ReportRoute: typeof ReportRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  PeekTokenRoute: typeof PeekTokenRoute
  ProposalTokenRoute: typeof ProposalTokenRoute
  ShareTokenRoute: typeof ShareTokenRoute
  ApiAuthLoginRoute: typeof ApiAuthLoginRoute
  ApiAuthLogoutRoute: typeof ApiAuthLogoutRoute
  ApiAuthSignupRoute: typeof ApiAuthSignupRoute
  ApiCronSweepRoute: typeof ApiCronSweepRoute
  ApiGmailCallbackRoute: typeof ApiGmailCallbackRoute
  ApiGmailConnectRoute: typeof ApiGmailConnectRoute
  ApiGmailDisconnectRoute: typeof ApiGmailDisconnectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/share/$token': {
      id: '/share/$token'
      path: '/share/$token'
      fullPath: '/share/$token'
      preLoaderRoute: typeof ShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposal/$token': {
      id: '/proposal/$token'
      path: '/proposal/$token'
      fullPath: '/proposal/$token'
      preLoaderRoute: typeof ProposalTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/peek/$token': {
      id: '/peek/$token'
      path: '/peek/$token'
      fullPath: '/peek/$token'
      preLoaderRoute: typeof PeekTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/today': {
      id: '/_app/today'
      path: '/today'
      fullPath: '/today'
      preLoaderRoute: typeof AppTodayRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/team': {
      id: '/_app/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AppTeamRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/pipeline': {
      id: '/_app/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AppPipelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/payroll': {
      id: '/_app/payroll'
      path: '/payroll'
      fullPath: '/payroll'
      preLoaderRoute: typeof AppPayrollRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/opportunities': {
      id: '/_app/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof AppOpportunitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/help': {
      id: '/_app/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/followups': {
      id: '/_app/followups'
      path: '/followups'
      fullPath: '/followups'
      preLoaderRoute: typeof AppFollowupsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/emails': {
      id: '/_app/emails'
      path: '/emails'
      fullPath: '/emails'
      preLoaderRoute: typeof AppEmailsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/discover': {
      id: '/_app/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof AppDiscoverRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contacts': {
      id: '/_app/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AppContactsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/companies': {
      id: '/_app/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof AppCompaniesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/calls': {
      id: '/_app/calls'
      path: '/calls'
      fullPath: '/calls'
      preLoaderRoute: typeof AppCallsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/billing': {
      id: '/_app/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/activities': {
      id: '/_app/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof AppActivitiesRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/gmail/disconnect': {
      id: '/api/gmail/disconnect'
      path: '/api/gmail/disconnect'
      fullPath: '/api/gmail/disconnect'
      preLoaderRoute: typeof ApiGmailDisconnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gmail/connect': {
      id: '/api/gmail/connect'
      path: '/api/gmail/connect'
      fullPath: '/api/gmail/connect'
      preLoaderRoute: typeof ApiGmailConnectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gmail/callback': {
      id: '/api/gmail/callback'
      path: '/api/gmail/callback'
      fullPath: '/api/gmail/callback'
      preLoaderRoute: typeof ApiGmailCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cron/sweep': {
      id: '/api/cron/sweep'
      path: '/api/cron/sweep'
      fullPath: '/api/cron/sweep'
      preLoaderRoute: typeof ApiCronSweepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/signup': {
      id: '/api/auth/signup'
      path: '/api/auth/signup'
      fullPath: '/api/auth/signup'
      preLoaderRoute: typeof ApiAuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/logout': {
      id: '/api/auth/logout'
      path: '/api/auth/logout'
      fullPath: '/api/auth/logout'
      preLoaderRoute: typeof ApiAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/login': {
      id: '/api/auth/login'
      path: '/api/auth/login'
      fullPath: '/api/auth/login'
      preLoaderRoute: typeof ApiAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/deals/$dealId': {
      id: '/_app/deals/$dealId'
      path: '/deals/$dealId'
      fullPath: '/deals/$dealId'
      preLoaderRoute: typeof AppDealsDealIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contacts_/$contactId': {
      id: '/_app/contacts_/$contactId'
      path: '/contacts/$contactId'
      fullPath: '/contacts/$contactId'
      preLoaderRoute: typeof AppContactsContactIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/companies_/$companyId': {
      id: '/_app/companies_/$companyId'
      path: '/companies/$companyId'
      fullPath: '/companies/$companyId'
      preLoaderRoute: typeof AppCompaniesCompanyIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppActivitiesRoute: typeof AppActivitiesRoute
  AppBillingRoute: typeof AppBillingRoute
  AppCallsRoute: typeof AppCallsRoute
  AppCompaniesRoute: typeof AppCompaniesRoute
  AppContactsRoute: typeof AppContactsRoute
  AppDiscoverRoute: typeof AppDiscoverRoute
  AppEmailsRoute: typeof AppEmailsRoute
  AppFollowupsRoute: typeof AppFollowupsRoute
  AppHelpRoute: typeof AppHelpRoute
  AppOpportunitiesRoute: typeof AppOpportunitiesRoute
  AppPayrollRoute: typeof AppPayrollRoute
  AppPipelineRoute: typeof AppPipelineRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTeamRoute: typeof AppTeamRoute
  AppTodayRoute: typeof AppTodayRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCompaniesCompanyIdRoute: typeof AppCompaniesCompanyIdRoute
  AppContactsContactIdRoute: typeof AppContactsContactIdRoute
  AppDealsDealIdRoute: typeof AppDealsDealIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivitiesRoute: AppActivitiesRoute,
  AppBillingRoute: AppBillingRoute,
  AppCallsRoute: AppCallsRoute,
  AppCompaniesRoute: AppCompaniesRoute,
  AppContactsRoute: AppContactsRoute,
  AppDiscoverRoute: AppDiscoverRoute,
  AppEmailsRoute: AppEmailsRoute,
  AppFollowupsRoute: AppFollowupsRoute,
  AppHelpRoute: AppHelpRoute,
  AppOpportunitiesRoute: AppOpportunitiesRoute,
  AppPayrollRoute: AppPayrollRoute,
  AppPipelineRoute: AppPipelineRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTeamRoute: AppTeamRoute,
  AppTodayRoute: AppTodayRoute,
  AppIndexRoute: AppIndexRoute,
  AppCompaniesCompanyIdRoute: AppCompaniesCompanyIdRoute,
  AppContactsContactIdRoute: AppContactsContactIdRoute,
  AppDealsDealIdRoute: AppDealsDealIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  ReportRoute: ReportRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  PeekTokenRoute: PeekTokenRoute,
  ProposalTokenRoute: ProposalTokenRoute,
  ShareTokenRoute: ShareTokenRoute,
  ApiAuthLoginRoute: ApiAuthLoginRoute,
  ApiAuthLogoutRoute: ApiAuthLogoutRoute,
  ApiAuthSignupRoute: ApiAuthSignupRoute,
  ApiCronSweepRoute: ApiCronSweepRoute,
  ApiGmailCallbackRoute: ApiGmailCallbackRoute,
  ApiGmailConnectRoute: ApiGmailConnectRoute,
  ApiGmailDisconnectRoute: ApiGmailDisconnectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
